name: T Hsu
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 6
paginate_path: /blog/page:num/
footer-links:
  twitter: thsubox
  email: tchsu1@gmail.com
  github: hsureads
  trello: hsureads
